'use strict';
const {initializeApp}=require('firebase-admin/app');const {getFirestore}=require('firebase-admin/firestore');const {getAuth}=require('firebase-admin/auth');const {getMessaging}=require('firebase-admin/messaging');const {onCall,HttpsError}=require('firebase-functions/v2/https');const {onDocumentUpdated}=require('firebase-functions/v2/firestore');const {onSchedule}=require('firebase-functions/v2/scheduler');const {setGlobalOptions}=require('firebase-functions/v2');const crypto=require('node:crypto');const D=require('./domain');
initializeApp();setGlobalOptions({region:'europe-west1',maxInstances:10});const db=getFirestore();const userRef=uid=>db.doc(`users/${uid}`);const famRef=(fid,col,id)=>db.doc(`families/${fid}/${col}/${id}`);
function fail(code,message){throw new HttpsError(code,message)}function dataOf(s){if(!s.exists)fail('not-found','הפריט אינו קיים');return s.data()}
async function member(tx,uid,now){const u=dataOf(await tx.get(userRef(uid))),m=dataOf(await tx.get(famRef(u.familyId,'members',uid)));if(m.activeDecision?.endsAt>now)fail('failed-precondition','יש החלטה פעילה. חוזרים לשאר האפליקציה כשהזמן מסתיים.');return {...u,...m,uid}}
function adult(m){if(m.role!=='adult')fail('permission-denied','הפעולה מיועדת למבוגרים במשפחה')}
function addPoints(tx,m,delta,event,now){if(delta===0)return;const next=m.balance+delta;if(next<0)fail('failed-precondition','אין מספיק נקודות');tx.update(famRef(m.familyId,'members',m.uid),{balance:next});tx.create(db.doc(`users/${m.uid}/ledger/${event}`),{delta,balanceAfter:next,createdAt:now})}
async function rateLimit(uid,now){const ref=db.doc(`rateLimits/${uid}`);await db.runTransaction(async tx=>{const s=await tx.get(ref),v=s.data(),same=v&&now-v.since<60000;if(same&&v.count>=100)fail('resource-exhausted','יותר מדי פעולות. נסו שוב בעוד דקה.');tx.set(ref,{since:same?v.since:now,count:same?v.count+1:1})})}
async function dispatch(uid,p,now){
 const action=D.text(p.action,40);if(action==='clock')return {now,questions:D.QUESTIONS};await rateLimit(uid,now);
 if(action==='restore'){const secret=D.text(p.secret,64);D.requireValue(/^[a-f0-9]{48}$/.test(secret),'קוד שחזור לא תקין');const rec=await db.doc(`recovery/${D.hash(secret)}`).get();if(!rec.exists)fail('not-found','קוד שחזור לא תקין');return {token:await getAuth().createCustomToken(rec.data().uid)}}
 if(action==='onboard'){
  const name=D.text(p.name,40),avatar=D.text(p.avatar,12),routines=D.routines(p.routines||[]),requestedRole=p.role;D.requireValue(['adult','child'].includes(requestedRole),'סוג משתמש לא תקין');
  const creating=!p.inviteCode,fid=db.collection('families').doc().id,recovery=D.secret(),inviteRef=creating?null:db.doc(`invitations/${D.hash(D.text(p.inviteCode,40).toUpperCase())}`);
  return db.runTransaction(async tx=>{if((await tx.get(userRef(uid))).exists)fail('already-exists','כבר נוצר פרופיל במכשיר הזה');let familyId=fid,role='adult';
   if(!creating){const inv=(await tx.get(inviteRef)).data();if(!inv||inv.usedBy||inv.expiresAt<now)fail('not-found','קוד ההזמנה אינו תקף');if(inv.role!==requestedRole)fail('permission-denied','סוג המשתמש אינו תואם להזמנה');familyId=inv.familyId;role=inv.role;if(!(await tx.get(db.doc(`families/${familyId}`))).exists)fail('not-found','המשפחה אינה קיימת');tx.update(inviteRef,{usedBy:uid})}
   else{if(requestedRole!=='adult')fail('permission-denied','מבוגר צריך ליצור את המשפחה');tx.create(db.doc(`families/${familyId}`),{name:D.text(p.familyName||'הבית שלנו',60),createdAt:now,ownerId:uid});for(const [title,icon] of [['ערב סרט לבחירתי','🎬'],['ללכת לישון מאוחר','🌙']])tx.create(db.collection(`families/${familyId}/products`).doc(),{title,description:'מתאמים יחד זמן מתאים למימוש',icon,price:1000,validDays:7,available:true})}
   tx.create(userRef(uid),{familyId,name,avatar,role,routines,recoveryHash:D.hash(recovery),createdAt:now});tx.create(famRef(familyId,'members',uid),{name,avatar,role,balance:0,createdAt:now});tx.create(db.doc(`recovery/${D.hash(recovery)}`),{uid,createdAt:now});return {familyId,recovery};
  });
 }
 if(action==='rotateRecovery'){const recovery=D.secret();await db.runTransaction(async tx=>{const m=await member(tx,uid,now);if(m.recoveryHash)tx.delete(db.doc(`recovery/${m.recoveryHash}`));tx.create(db.doc(`recovery/${D.hash(recovery)}`),{uid,createdAt:now});tx.update(userRef(uid),{recoveryHash:D.hash(recovery)})});return {recovery}}
 return db.runTransaction(async tx=>{const m=await member(tx,uid,now),fid=m.familyId;
  switch(action){
   case 'invite':{adult(m);const role=p.role;D.requireValue(['adult','child'].includes(role),'סוג הזמנה לא תקין');const code=D.code();tx.create(db.doc(`invitations/${D.hash(code)}`),{familyId:fid,role,createdBy:uid,expiresAt:now+86400000});return {code,role}}
   case 'profile':{const changes={name:D.text(p.name,40),avatar:D.text(p.avatar,12)};tx.update(userRef(uid),changes);tx.update(famRef(fid,'members',uid),changes);return {}}
   case 'routines':tx.update(userRef(uid),{routines:D.routines(p.routines)});return {};
   case 'routineCheck':{const rid=D.id(p.id),kind=p.kind;D.requireValue(['morning','evening'].includes(kind),'רוטינה לא תקינה');const date=D.dateAt(now),day=new Date(`${date}T12:00:00Z`).getUTCDay()||7,r=m.routines.find(x=>x.id===rid&&x.kind===kind&&x.days.includes(day));if(!r)fail('failed-precondition','השלב אינו חלק מהרוטינה של היום');const ref=db.doc(`users/${uid}/routineDays/${date}_${kind}`),s=await tx.get(ref),steps=s.data()?.steps||{};steps[rid]={title:steps[rid]?.title||r.title,done:p.done===true,updatedAt:now};tx.set(ref,{date,kind,steps});return {}}
   case 'createTask':{const assignee=D.id(p.assignee);dataOf(await tx.get(famRef(fid,'members',assignee)));const ref=famRef(fid,'tasks',D.id(p.requestId)),old=await tx.get(ref);if(old.exists){if(old.data().giver!==uid)fail('already-exists','מזהה בשימוש');return {}}tx.create(ref,{title:D.text(p.title),assignee,giver:uid,points:D.taskPoints(uid,assignee,p.points),done:false,createdAt:now});return {}}
   case 'completeTask':{const ref=famRef(fid,'tasks',D.id(p.id)),t=dataOf(await tx.get(ref));if(t.assignee!==uid)fail('permission-denied','רק מי שקיבל את המשימה יכול להשלים אותה');if(t.done)return {};tx.update(ref,{done:true,completedAt:now});addPoints(tx,m,t.points,`task_${ref.id}`,now);return {}}
   case 'deleteTask':{const ref=famRef(fid,'tasks',D.id(p.id)),t=dataOf(await tx.get(ref));if(t.done||t.giver!==uid)fail('permission-denied','אפשר למחוק רק משימה פתוחה שיצרת');tx.delete(ref);return {}}
   case 'summary':{const date=D.editableDate(p.date,now);D.requireValue(D.MOODS.includes(p.mood),'בחרו מצב רוח');const ref=db.doc(`users/${uid}/summaries/${date}`),old=await tx.get(ref),result=D.summaryDelta(old.data(),p.answers);tx.set(ref,{...result,date,mood:p.mood,questionVersion:1,questions:D.QUESTIONS,updatedAt:now});tx.set(famRef(fid,'moods',`${date}_${uid}`),{date,uid,mood:p.mood});addPoints(tx,m,result.delta,`summary_${date}_${result.awardedQuestions.length}`,now);return {awarded:result.delta}}
   case 'saveProduct':{adult(m);const productId=p.id?D.id(p.id):db.collection('x').doc().id;tx.set(famRef(fid,'products',productId),{title:D.text(p.title),description:D.text(p.description||'',500,true),icon:D.text(p.icon||'🎁',12),price:D.integer(p.price,1,100000),validDays:D.integer(p.validDays,1,365),available:p.available===true});return {}}
   case 'deleteProduct':adult(m);tx.delete(famRef(fid,'products',D.id(p.id)));return {};
   case 'buy':{const ref=famRef(fid,'vouchers',D.id(p.requestId)),old=await tx.get(ref);if(old.exists){if(old.data().owner!==uid)fail('already-exists','מזהה בשימוש');return {}}const product=dataOf(await tx.get(famRef(fid,'products',D.id(p.id))));if(!product.available)fail('failed-precondition','המוצר אינו זמין כרגע');addPoints(tx,m,-product.price,`buy_${ref.id}`,now);tx.create(ref,{...product,productId:p.id,owner:uid,status:'available',boughtAt:now,expiresAt:now+product.validDays*86400000,rejectedBy:[]});return {}}
   case 'redeem':{const ref=famRef(fid,'vouchers',D.id(p.id)),v=dataOf(await tx.get(ref));if(v.owner!==uid)fail('permission-denied','השובר אינו שלך');if(v.expiresAt<=now)fail('failed-precondition','תוקף השובר פג');if(v.status==='pending')return {};if(v.status!=='available')fail('failed-precondition','השובר כבר מומש');tx.update(ref,{status:'pending',requestedAt:now});return {}}
   case 'approve':case 'reject':{const ref=famRef(fid,'vouchers',D.id(p.id)),v=dataOf(await tx.get(ref));if(v.owner===uid)fail('permission-denied','אי אפשר לאשר לעצמך');if(v.status==='redeemed')return {};if(v.status!=='pending'||v.expiresAt<=now)fail('failed-precondition','בקשת המימוש אינה פעילה');tx.update(ref,action==='approve'?{status:'redeemed',approvedBy:uid,redeemedAt:now}:{rejectedBy:[...new Set([...(v.rejectedBy||[]),uid])]});return {}}
   case 'createList':{const other=D.id(p.other);if(other===uid)fail('invalid-argument','צריך לבחור בן משפחה נוסף');dataOf(await tx.get(famRef(fid,'members',other)));const ref=db.collection('privateLists').doc();tx.create(ref,{familyId:fid,title:D.text(p.title),participantIds:[uid,other],createdAt:now});return {id:ref.id}}
   case 'listItem':case 'deleteListItem':{const listId=D.id(p.listId),list=dataOf(await tx.get(db.doc(`privateLists/${listId}`)));if(list.familyId!==fid||!list.participantIds.includes(uid))fail('permission-denied','אין גישה לרשימה');const itemId=p.id?D.id(p.id):db.collection('x').doc().id,ref=db.doc(`privateLists/${listId}/items/${itemId}`);if(action==='deleteListItem')tx.delete(ref);else tx.set(ref,{title:D.text(p.title),done:p.done===true,updatedAt:now});return {}}
   case 'decisionInvite':{const other=D.id(p.other);if(other===uid)fail('invalid-argument','צריך לבחור בן משפחה נוסף');const o=dataOf(await tx.get(famRef(fid,'members',other)));if(o.activeDecision?.endsAt>now)fail('failed-precondition','בן המשפחה כבר בהגרלה פעילה');const minutes=D.integer(p.minutes,1,180),ref=famRef(fid,'decisions',D.id(p.requestId)),old=await tx.get(ref);if(old.exists){if(old.data().creator!==uid)fail('already-exists','מזהה בשימוש');return {id:ref.id}}tx.create(ref,{participantIds:[uid,other],creator:uid,other,minutes,status:'waiting',createdAt:now,expiresAt:now+300000});return {id:ref.id}}
   case 'decisionAccept':{const ref=famRef(fid,'decisions',D.id(p.id)),d=dataOf(await tx.get(ref));if(d.other!==uid)fail('permission-denied','ההזמנה מיועדת למשתמש אחר');if(d.status!=='waiting'||d.expiresAt<=now)fail('failed-precondition','ההזמנה כבר נסגרה');const creator=dataOf(await tx.get(famRef(fid,'members',d.creator)));if(creator.activeDecision?.endsAt>now)fail('failed-precondition','כבר יש החלטה פעילה');const startsAt=now+5000,endsAt=startsAt+d.minutes*60000,winner=d.participantIds[crypto.randomInt(2)],activeDecision={id:ref.id,startsAt,endsAt,winner,minutes:d.minutes,participantIds:d.participantIds};tx.update(ref,{...activeDecision,status:'active'});for(const participant of d.participantIds)tx.update(famRef(fid,'members',participant),{activeDecision});tx.create(db.doc(`decisionExpirations/${ref.id}`),{familyId:fid,at:endsAt,participantIds:d.participantIds});return activeDecision}
   default:fail('invalid-argument','פעולה לא מוכרת');
  }
 });
}
exports.familyApi=onCall({timeoutSeconds:30},async request=>{if(!request.auth)fail('unauthenticated','נדרשת כניסה');try{return await dispatch(request.auth.uid,request.data||{},Date.now())}catch(e){if(e instanceof HttpsError)throw e;if(e.code==='invalid-argument')fail('invalid-argument',e.message);console.error('Family operation failed',{code:e.code});fail('internal','הפעולה לא נשמרה. נסו שוב.')}});
async function notify(uids,title,body,tag){const tokens=[];for(const uid of uids){const docs=await db.collection(`users/${uid}/devices`).get();docs.forEach(d=>tokens.push(d.data().token))}for(let i=0;i<tokens.length;i+=500)await getMessaging().sendEachForMulticast({tokens:tokens.slice(i,i+500),notification:{title,body},android:{priority:'high',notification:{channelId:'family',tag}}})}
exports.redemptionNotification=onDocumentUpdated('families/{fid}/vouchers/{voucher}',async event=>{const before=event.data.before.data(),after=event.data.after.data();if(before.status===after.status||after.status!=='pending')return;const members=await db.collection(`families/${event.params.fid}/members`).get();await notify(members.docs.map(d=>d.id).filter(uid=>uid!==after.owner),'בקשת מימוש חדשה',`מי מאשר: ${after.title}?`,`voucher_${event.params.voucher}`)});
exports.decisionFinished=onSchedule({schedule:'every 1 minutes',timeZone:'Asia/Jerusalem'},async()=>{const due=await db.collection('decisionExpirations').where('at','<=',Date.now()).limit(100).get();for(const d of due.docs){const v=d.data();await notify(v.participantIds,'נגמר הזמן!','חוזרים לדמוקרטיה.',`decision_${d.id}`);await d.ref.delete()}});
exports._dispatch=dispatch;
